version: "3.1"

services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "13306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/sql
volumes:
  db-data:
