version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "13306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
